# Cloudflare Worker for Weekly Backup
name = "vehicle-management-auto-backup"
main = "auto-backup.js"
compatibility_date = "2025-10-16"

# Cron Trigger: Every Sunday at 02:00 Vietnam Time (UTC+7)
# Vietnam 02:00 Sunday = UTC 19:00 Saturday
# Cron format: minute hour day month dayOfWeek (0=Sunday, 6=Saturday)
[triggers]
crons = ["0 19 * * 6"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "vehicle-management-db"
database_id = "your-database-id-here"

# R2 Bucket for backup storage (optional)
[[r2_buckets]]
binding = "BACKUP_BUCKET"
bucket_name = "vehicle-management-backups"

# Environment variables
[vars]
BACKUP_EMAIL = "your-email@example.com"
